/* global React, Icon, Shared, BaseTable, CellRenderers */
const { useState } = React;
const { Chip, PersonChip, Kbd, formatBRDate, formatBRDateTime, EmptyState } = Shared;

// =====================================================
// IMPORTAR (drop zone + preview + apply)
// =====================================================
function ImportarPage() {
  const [step, setStep] = useState(2); // 0=drop, 1=mapping, 2=preview
  const [base, setBase] = useState('Processos');
  const RPDATA = window.RPDATA;

  const previewRows = RPDATA.IMPORT_PREVIEW;
  const summary = {
    total: previewRows.length,
    novos: previewRows.filter((r) => r.action === 'create').length,
    atualizar: previewRows.filter((r) => r.action === 'update').length,
    conflito: previewRows.filter((r) => r.action === 'conflict').length,
    ignorar: previewRows.filter((r) => r.action === 'skip').length,
  };

  return React.createElement('div', { className: 'page', 'data-screen-label': '07 Importar' },
    React.createElement('div', { className: 'toolbar' },
      React.createElement('h1', { className: 'toolbar-title' }, 'Importar planilha'),
      React.createElement('span', { className: 'toolbar-meta' }, 'Preview · processos.xlsx · 47,2 KB'),
      React.createElement('div', { className: 'toolbar-spacer' }),
      React.createElement('button', { className: 'btn btn-ghost', onClick: () => setStep(0) },
        React.createElement(Icon.X, { size: 12 }), 'Cancelar'),
    ),
    React.createElement('div', { className: 'import-stepper' },
      ['Carregar arquivo', 'Mapear colunas', 'Revisar e aplicar'].map((label, i) =>
        React.createElement('div', { key: i, className: `stepper-item ${i === step ? 'active' : i < step ? 'done' : ''}` },
          React.createElement('span', { className: 'stepper-dot' }, i < step ? React.createElement(Icon.Check, { size: 12 }) : i + 1),
          React.createElement('span', null, label),
          i < 2 && React.createElement('span', { className: 'stepper-line' }),
        ),
      ),
    ),
    step === 0 && React.createElement('div', { className: 'page-body' },
      React.createElement('div', { className: 'dropzone' },
        React.createElement(Icon.Upload, { size: 28 }),
        React.createElement('div', { className: 'dz-title' }, 'Arraste a planilha ou clique para selecionar'),
        React.createElement('div', { className: 'dz-hint' }, 'XLSX ou CSV · até 5 MB · primeira linha = cabeçalho'),
        React.createElement('button', { className: 'btn btn-primary', onClick: () => setStep(2) },
          React.createElement(Icon.Upload, { size: 12 }), 'Selecionar arquivo'),
      ),
    ),
    (step === 1 || step === 2) && React.createElement('div', { className: 'page-body' },
      React.createElement('div', { className: 'panel-strip' },
        React.createElement('div', { className: 'panel-strip-item' },
          React.createElement('span', { className: 'pi-eyebrow' }, 'Arquivo'),
          React.createElement('span', { className: 'pi-value mono' }, 'processos.xlsx'),
          React.createElement('span', { className: 'pi-meta' }, '203 linhas · 12 colunas'),
        ),
        React.createElement('div', { className: 'panel-strip-item' },
          React.createElement('span', { className: 'pi-eyebrow' }, 'Base de destino'),
          React.createElement('select', { className: 'select', value: base, onChange: (e) => setBase(e.target.value) },
            ['Processos', 'Clientes', 'Tarefas', 'Catálogo'].map((b) => React.createElement('option', { key: b }, b)),
          ),
        ),
        React.createElement('div', { className: 'panel-strip-item' },
          React.createElement('span', { className: 'pi-eyebrow' }, 'Política de duplicados'),
          React.createElement('select', { className: 'select', defaultValue: 'CNJ' },
            ['CNJ (chave única)', 'CPF', 'E-mail'].map((b) => React.createElement('option', { key: b }, b)),
          ),
        ),
        React.createElement('div', { className: 'panel-strip-item summary' },
          React.createElement('span', { className: 'pi-eyebrow' }, 'Resumo do preview'),
          React.createElement('div', { style: { display: 'flex', gap: 12, alignItems: 'baseline' } },
            React.createElement('span', { style: { fontFamily: 'var(--font-display)', fontSize: 22, color: 'var(--app-fg)' } }, summary.total),
            React.createElement('span', { className: 'pi-meta' }, `${summary.novos} novos · ${summary.atualizar} atualizar · `,
              React.createElement('span', { style: { color: 'var(--app-warning)' } }, `${summary.conflito} conflito`),
            ),
          ),
        ),
      ),
      React.createElement('div', { className: 'tbl-wrap', style: { marginTop: 16 } },
        React.createElement('table', { className: 'tbl compact import-tbl' },
          React.createElement('thead', null,
            React.createElement('tr', null,
              React.createElement('th', { style: { width: 32 } }, ''),
              React.createElement('th', { style: { width: 90 } }, 'Ação'),
              React.createElement('th', null, 'CNJ'),
              React.createElement('th', null, 'Cliente'),
              React.createElement('th', null, 'Fase'),
              React.createElement('th', null, 'Status'),
              React.createElement('th', null, 'Valor'),
              React.createElement('th', null, 'Notas'),
            ),
          ),
          React.createElement('tbody', null,
            previewRows.map((r, i) => {
              const map = {
                create: { color: 'green', label: 'Criar', icon: '+' },
                update: { color: 'blue', label: 'Atualizar', icon: '~' },
                conflict: { color: 'amber', label: 'Conflito', icon: '!' },
                skip: { color: 'gray', label: 'Ignorar', icon: '–' },
              };
              const m = map[r.action];
              return React.createElement('tr', { key: i, className: r.action === 'conflict' ? 'row-warn' : '' },
                React.createElement('td', null,
                  React.createElement('input', { type: 'checkbox', defaultChecked: r.action !== 'skip' && r.action !== 'conflict' })),
                React.createElement('td', null, React.createElement(Chip, { value: m.label, color: m.color })),
                React.createElement('td', { className: 'cell-mono' }, r.cnj),
                React.createElement('td', null, r.cliente),
                React.createElement('td', null, React.createElement(Chip, { value: r.fase, color: 'petrol' })),
                React.createElement('td', null, React.createElement(CellRenderers.ProcStatusCell, { value: r.status })),
                React.createElement('td', { className: 'cell-num mono' }, r.valor),
                React.createElement('td', null, r.note ? React.createElement('span', { style: { color: r.action === 'conflict' ? 'var(--app-warning)' : 'var(--app-fg-subtle)', fontSize: 11 } }, r.note) : '—'),
              );
            }),
          ),
        ),
      ),
      React.createElement('div', { className: 'foot-actions' },
        React.createElement('span', { style: { fontSize: 12, color: 'var(--app-fg-subtle)' } },
          `${summary.total - summary.ignorar} linhas serão aplicadas no Notion · operação registrada em Logs`),
        React.createElement('div', { className: 'toolbar-spacer' }),
        React.createElement('button', { className: 'btn btn-ghost' }, 'Voltar'),
        React.createElement('button', { className: 'btn btn-primary' },
          React.createElement(Icon.Check, { size: 12 }),
          `Aplicar ${summary.total - summary.ignorar} alterações`,
          React.createElement(Kbd, null, 'Ctrl+↵'),
        ),
      ),
    ),
  );
}

// =====================================================
// LOGS
// =====================================================
function LogsPage() {
  const [search, setSearch] = useState('');
  const [filterTipo, setFilterTipo] = useState('');
  const RPDATA = window.RPDATA;

  let rows = RPDATA.LOGS_LIST;
  if (search) {
    const q = search.toLowerCase();
    rows = rows.filter((r) => Object.values(r).some((v) => v && String(v).toLowerCase().includes(q)));
  }
  if (filterTipo) rows = rows.filter((r) => r.base === filterTipo);

  return React.createElement('div', { className: 'page', 'data-screen-label': '08 Logs' },
    React.createElement('div', { className: 'toolbar' },
      React.createElement('h1', { className: 'toolbar-title' }, 'Logs de alterações'),
      React.createElement('span', { className: 'toolbar-meta' }, `${rows.length} eventos · últimos 30 dias`),
      React.createElement('div', { className: 'toolbar-spacer' }),
      React.createElement('div', { className: 'search-input' },
        React.createElement(Icon.Search),
        React.createElement('input', { className: 'input', value: search, onChange: (e) => setSearch(e.target.value), placeholder: 'Buscar em logs…' }),
      ),
      React.createElement('select', { className: 'select', value: filterTipo, onChange: (e) => setFilterTipo(e.target.value) },
        React.createElement('option', { value: '' }, 'Todas as bases'),
        ['Processos', 'Tarefas', 'Clientes', 'Catálogo'].map((t) => React.createElement('option', { key: t, value: t }, t)),
      ),
      React.createElement('button', { className: 'btn btn-ghost' },
        React.createElement(Icon.Download, { size: 12 }), 'Exportar CSV'),
    ),
    React.createElement('div', { className: 'tbl-wrap' },
      React.createElement('table', { className: 'tbl compact' },
        React.createElement('thead', null,
          React.createElement('tr', null,
            React.createElement('th', { style: { width: 150 } }, 'Quando'),
            React.createElement('th', { style: { width: 100 } }, 'Base'),
            React.createElement('th', { style: { width: 90 } }, 'Status'),
            React.createElement('th', null, 'Propriedade'),
            React.createElement('th', null, 'Antes → Depois'),
            React.createElement('th', { style: { width: 200 } }, 'Identificador'),
            React.createElement('th', { style: { width: 100 } }, 'Usuário'),
            React.createElement('th', { style: { width: 90 } }, ''),
          ),
        ),
        React.createElement('tbody', null,
          rows.map((l) => React.createElement('tr', { key: l.id, className: l.status === 'ERRO' ? 'row-danger' : '' },
            React.createElement('td', { className: 'cell-mono', style: { color: 'var(--app-fg-muted)', fontSize: 11 } }, formatBRDateTime(l.timestamp)),
            React.createElement('td', null, React.createElement(Chip, { value: l.base, color: l.base === 'Processos' ? 'blue' : l.base === 'Tarefas' ? 'petrol' : l.base === 'Clientes' ? 'green' : 'gray' })),
            React.createElement('td', null,
              React.createElement('span', { style: { display: 'inline-flex', alignItems: 'center', gap: 6, fontSize: 12, color: l.status === 'ERRO' ? 'var(--app-danger)' : 'var(--app-success)' } },
                React.createElement('span', { style: { width: 6, height: 6, borderRadius: 99, background: 'currentColor' } }),
                l.status === 'OK' ? 'OK' : 'Erro')),
            React.createElement('td', null, React.createElement('strong', { style: { fontWeight: 500 } }, l.propriedade)),
            React.createElement('td', { style: { fontSize: 12 } },
              React.createElement('span', { style: { color: 'var(--app-fg-subtle)', textDecoration: 'line-through' } }, l.valorAntigo),
              React.createElement('span', { style: { color: 'var(--app-fg-subtle)', margin: '0 6px' } }, '→'),
              React.createElement('span', { style: { color: 'var(--app-fg)' } }, l.valorNovo),
              l.mensagemErro && React.createElement('div', { style: { fontSize: 11, color: 'var(--app-danger)', marginTop: 2, fontFamily: 'var(--font-mono)' } }, l.mensagemErro),
            ),
            React.createElement('td', { className: 'cell-mono', style: { fontSize: 11, color: 'var(--app-fg-muted)' } }, l.identificador.slice(0, 18) + '…'),
            React.createElement('td', null, React.createElement(PersonChip, { person: l.usuario })),
            React.createElement('td', null,
              l.status === 'OK' && !l.revertido && React.createElement('button', { className: 'btn btn-ghost', style: { height: 22, padding: '0 8px', fontSize: 11 } },
                React.createElement(Icon.Undo, { size: 11 }), 'Reverter'),
            ),
          )),
        ),
      ),
    ),
  );
}

// =====================================================
// CONFIGURAÇÕES
// =====================================================
function ConfiguracoesPage({ tweak, setTweak }) {
  const [section, setSection] = useState('integracao');

  const sections = [
    { id: 'integracao', label: 'Integração Notion', icon: Icon.File },
    { id: 'sync', label: 'Sincronização', icon: Icon.Refresh },
    { id: 'aparencia', label: 'Aparência', icon: Icon.Sun },
    { id: 'usuarios', label: 'Usuários', icon: Icon.Users },
    { id: 'atalhos', label: 'Atalhos de teclado', icon: Icon.Settings },
    { id: 'sobre', label: 'Sobre', icon: Icon.Info },
  ];

  return React.createElement('div', { className: 'page', 'data-screen-label': '09 Configurações' },
    React.createElement('div', { className: 'toolbar' },
      React.createElement('h1', { className: 'toolbar-title' }, 'Configurações'),
      React.createElement('span', { className: 'toolbar-meta' }, 'Estação Leonardo · DESKTOP-LR21K8'),
    ),
    React.createElement('div', { className: 'config-layout' },
      React.createElement('nav', { className: 'config-nav' },
        sections.map((s) =>
          React.createElement('button', { key: s.id, className: `config-nav-item ${section === s.id ? 'active' : ''}`, onClick: () => setSection(s.id) },
            React.createElement(s.icon, { size: 14 }),
            React.createElement('span', null, s.label),
          ),
        ),
      ),
      React.createElement('div', { className: 'config-body' },
        section === 'integracao' && React.createElement(React.Fragment, null,
          React.createElement('div', { className: 'config-section' },
            React.createElement('div', { className: 'config-section-head' },
              React.createElement('h2', null, 'Conexão com o Notion'),
              React.createElement('span', { className: 'status-pill ok' }, React.createElement('span', { className: 'sp-dot' }), 'Conectado'),
            ),
            React.createElement('p', { className: 'config-help' }, 'O token de integração é armazenado localmente, criptografado pelo Windows DPAPI. Nenhum dado do escritório passa por servidor externo.'),
            React.createElement('div', { className: 'config-row' },
              React.createElement('label', null, 'Workspace'),
              React.createElement('div', { className: 'config-value' },
                React.createElement('strong', null, 'RPADV — Operações'),
                React.createElement('span', { className: 'subtle', style: { marginLeft: 8 } }, 'workspace ID notion://7e2f…3a01'),
              ),
            ),
            React.createElement('div', { className: 'config-row' },
              React.createElement('label', null, 'Token de integração'),
              React.createElement('div', { className: 'config-value mono', style: { letterSpacing: '0.05em', color: 'var(--app-fg-muted)' } },
                'secret_••••••••••••••••••••••••••••••••••f4G8',
                React.createElement('button', { className: 'btn btn-ghost', style: { marginLeft: 8 } }, 'Rotacionar'),
              ),
            ),
            React.createElement('div', { className: 'config-row' },
              React.createElement('label', null, 'Bases conectadas'),
              React.createElement('div', { className: 'config-value' },
                ['Processos', 'Clientes', 'Tarefas', 'Catálogo'].map((b) => React.createElement(Chip, { key: b, value: b, color: 'green' })),
              ),
            ),
            React.createElement('div', { className: 'config-row' },
              React.createElement('label', null, 'Permissões concedidas'),
              React.createElement('div', { className: 'config-value' },
                React.createElement('span', null, 'Read content · Update content · Read user info'),
              ),
            ),
          ),
        ),
        section === 'sync' && React.createElement(React.Fragment, null,
          React.createElement('div', { className: 'config-section' },
            React.createElement('h2', null, 'Comportamento da sincronização'),
            React.createElement('div', { className: 'config-row' },
              React.createElement('label', null, 'Intervalo automático'),
              React.createElement('select', { className: 'select', defaultValue: '15m' },
                React.createElement('option', { value: '5m' }, '5 minutos'),
                React.createElement('option', { value: '15m' }, '15 minutos'),
                React.createElement('option', { value: '30m' }, '30 minutos'),
                React.createElement('option', { value: 'manual' }, 'Apenas manual'),
              ),
            ),
            React.createElement('div', { className: 'config-row' },
              React.createElement('label', null, 'Cache local'),
              React.createElement('div', { className: 'config-value' },
                React.createElement('strong', { className: 'mono' }, '142,8 MB'),
                React.createElement('span', { className: 'subtle', style: { marginLeft: 8 } }, '· última limpeza em 12/03/2025'),
                React.createElement('button', { className: 'btn btn-ghost', style: { marginLeft: 8 } },
                  React.createElement(Icon.Trash, { size: 12 }), 'Limpar cache'),
              ),
            ),
            React.createElement('div', { className: 'config-row' },
              React.createElement('label', null, 'Conflitos'),
              React.createElement('div', { className: 'config-value' },
                React.createElement('label', { style: { display: 'inline-flex', alignItems: 'center', gap: 8, marginRight: 16 } },
                  React.createElement('input', { type: 'radio', name: 'conflict', defaultChecked: true }), 'Sempre perguntar'),
                React.createElement('label', { style: { display: 'inline-flex', alignItems: 'center', gap: 8, marginRight: 16 } },
                  React.createElement('input', { type: 'radio', name: 'conflict' }), 'Notion sempre vence'),
                React.createElement('label', { style: { display: 'inline-flex', alignItems: 'center', gap: 8 } },
                  React.createElement('input', { type: 'radio', name: 'conflict' }), 'Local sempre vence'),
              ),
            ),
            React.createElement('div', { className: 'config-row' },
              React.createElement('label', null, 'Notificações'),
              React.createElement('div', { className: 'config-value' },
                ['Sync com erro', 'Conflito de edição', 'Tarefa < 24h', 'Token expirado'].map((s, i) =>
                  React.createElement('label', { key: s, style: { display: 'inline-flex', alignItems: 'center', gap: 6, marginRight: 12, fontSize: 12 } },
                    React.createElement('input', { type: 'checkbox', defaultChecked: i !== 2 }), s),
                ),
              ),
            ),
          ),
        ),
        section === 'aparencia' && React.createElement('div', { className: 'config-section' },
          React.createElement('h2', null, 'Aparência'),
          React.createElement('div', { className: 'config-row' },
            React.createElement('label', null, 'Tema'),
            React.createElement('div', { className: 'config-value' },
              ['light', 'dark', 'auto'].map((t) =>
                React.createElement('label', { key: t, className: `theme-card ${tweak.theme === t ? 'active' : ''}`, onClick: () => setTweak({ theme: t }) },
                  React.createElement('div', { className: `theme-preview theme-${t}` },
                    React.createElement('span'), React.createElement('span'), React.createElement('span'),
                  ),
                  React.createElement('span', { style: { textTransform: 'capitalize' } }, t === 'light' ? 'Claro' : t === 'dark' ? 'Escuro' : 'Auto (sistema)'),
                ),
              ),
            ),
          ),
          React.createElement('div', { className: 'config-row' },
            React.createElement('label', null, 'Densidade da tabela'),
            React.createElement('div', { className: 'config-value' },
              ['compact', 'comfort'].map((t) =>
                React.createElement('label', { key: t, style: { display: 'inline-flex', alignItems: 'center', gap: 8, marginRight: 16 } },
                  React.createElement('input', { type: 'radio', name: 'density', checked: tweak.density === t, onChange: () => setTweak({ density: t }) }),
                  t === 'compact' ? 'Compacta (28px)' : 'Confortável (36px)',
                ),
              ),
            ),
          ),
          React.createElement('div', { className: 'config-row' },
            React.createElement('label', null, 'Tamanho da fonte'),
            React.createElement('div', { className: 'config-value' },
              React.createElement('input', { type: 'range', min: 12, max: 16, step: 1, value: tweak.fontSize || 13, onChange: (e) => setTweak({ fontSize: +e.target.value }), style: { width: 200 } }),
              React.createElement('span', { className: 'mono', style: { marginLeft: 12, color: 'var(--app-fg-muted)' } }, `${tweak.fontSize || 13}px`),
            ),
          ),
        ),
        section === 'atalhos' && React.createElement('div', { className: 'config-section' },
          React.createElement('h2', null, 'Atalhos de teclado'),
          React.createElement('div', { className: 'shortcuts-grid' },
            [
              ['Ctrl+P', 'Abrir busca de processos'],
              ['Ctrl+T', 'Abrir busca de tarefas'],
              ['Ctrl+K', 'Paleta de comandos'],
              ['Ctrl+S', 'Salvar alterações pendentes'],
              ['Ctrl+R', 'Sincronizar agora'],
              ['Ctrl+,', 'Abrir configurações'],
              ['Ctrl+F', 'Buscar na tabela atual'],
              ['Ctrl+E', 'Exportar tabela visível'],
              ['Esc', 'Cancelar edição inline'],
              ['Enter', 'Confirmar edição inline'],
              ['?', 'Mostrar todos os atalhos'],
              ['Alt+1..6', 'Ir para Dashboard, Processos, …'],
            ].map(([k, l]) => React.createElement('div', { key: k, className: 'shortcut-row' },
              React.createElement('span', { className: 'shortcut-keys' },
                k.split('+').map((part, i) => React.createElement(React.Fragment, { key: i },
                  i > 0 && React.createElement('span', { style: { color: 'var(--app-fg-subtle)' } }, '+'),
                  React.createElement(Kbd, null, part),
                )),
              ),
              React.createElement('span', { className: 'shortcut-label' }, l),
            )),
          ),
        ),
        section === 'usuarios' && React.createElement('div', { className: 'config-section' },
          React.createElement('h2', null, 'Usuários do escritório'),
          React.createElement('p', { className: 'config-help' }, 'Estas pessoas aparecem em "Responsável" nas tabelas. Sincronizadas a partir do Notion.'),
          React.createElement('table', { className: 'tbl compact', style: { marginTop: 12 } },
            React.createElement('thead', null, React.createElement('tr', null,
              React.createElement('th', null, 'Nome'),
              React.createElement('th', null, 'E-mail'),
              React.createElement('th', null, 'Papel'),
              React.createElement('th', null, 'Último acesso'),
            )),
            React.createElement('tbody', null,
              window.RPDATA.PESSOAS.map((p, i) => React.createElement('tr', { key: p.id },
                React.createElement('td', null, React.createElement(PersonChip, { person: p.id })),
                React.createElement('td', { style: { color: 'var(--app-fg-muted)' } }, p.name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/\s+/g, '.') + '@rpadv.adv.br'),
                React.createElement('td', null, React.createElement(Chip, { value: p.role, color: p.role.includes('Admin') ? 'red' : p.role.includes('Sócio') ? 'purple' : 'petrol' })),
                React.createElement('td', { className: 'mono', style: { color: 'var(--app-fg-subtle)', fontSize: 11 } }, ['hoje · 09:42', 'hoje · 10:15', 'ontem · 17:30', 'hoje · 11:02', 'hoje · 08:55'][i] || '—'),
              )),
            ),
          ),
        ),
        section === 'sobre' && React.createElement('div', { className: 'config-section' },
          React.createElement('h2', null, 'Sobre'),
          React.createElement('p', { style: { fontSize: 13, color: 'var(--app-fg-muted)', lineHeight: 1.6, maxWidth: 560 } },
            'RPADV Notion Companion · v0.4.2 (interno · não distribuído).',
            React.createElement('br'),
            'Aplicativo Windows desenvolvido sob medida para o escritório Rohrbacher de Almeida Advogados Associados.'),
          React.createElement('div', { className: 'config-row', style: { marginTop: 24 } },
            React.createElement('label', null, 'Versão'),
            React.createElement('div', { className: 'config-value mono' }, '0.4.2 (build 2025-03-18)'),
          ),
          React.createElement('div', { className: 'config-row' },
            React.createElement('label', null, 'Licenciado para'),
            React.createElement('div', { className: 'config-value' }, 'RPADV — 4 estações ativas'),
          ),
        ),
      ),
    ),
  );
}

window.AdminPages = { ImportarPage, LogsPage, ConfiguracoesPage };
